name: e2e pipeline
run-name: Build, Deploy, Test from user @${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ vars.PORT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
    
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Unit Tests
        run: npm test

      - name: Run E2E Tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ env.ACT != 'true' }}
        with: 
          name: simulate build
          path: ./dist
          retention-days: 3

  analyze:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      # allow read info from the current workflow, likewise previous executions, artifacts, and CodeQL to query the execution context
      actions: read
      # allow read files of the repo, access to historical commits, download repository content via API
      contents: read
      # allow analyze and the result be uploaded to Github/security/code scanning
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: typescript
    
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
    
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
    
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:typescript"

  #Render is used to deploy the API and handles the Continuous Deployment (CD) process.
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: test

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: simulate build
          path: ./dist

      - name: Deploy (simulated)
        run: |
          echo "Deploying build to TEST environment"
          ls -la dist
    
  #This step normally runs at the end of the build or deployment process.
  #It is commonly used in projects that generate deployable artifacts,
  #such as installers or Docker images, to clean temporary resources.
  cleanup:
    needs: deploy
    runs-on: ubuntu-latest
    environment: test
    
    steps:
      - name: cleanup ${{ github.env }}
        if: always()
        run: echo "cleanup example"